[package]
name = "rayt_rust2"
version = "0.1.0"
authors = ["mebiusbox <mebiusbox@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.23.12"
minifb = "0.19.2"
rand = "0.8.3"
rayon = "1.5.0"
